# Generated by Django 5.0.6 on 2024-06-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodzones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodExtent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='geotiffs/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FloodZone',
        ),
    ]
