# Generated by Django 5.0.6 on 2024-06-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloodRiskZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('raster', models.FileField(upload_to='rasters/')),
                ('classified_raster', models.ImageField(upload_to='classified_rasters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
